N차원 배열 연산법

3-1. 배열의 연산1

In [ ]:
import numpy as np
# 연산을 위해서는 두 배열의 shape이 같아야한다.
#쉐입이 다른  배열의 연산을 가능하게 해주는 브로드캐스팅 기능이 있음

#numpy는 파이썬 기본 연산자를 n차원 배열, 즉 행렬이나 텐서 간의 연산이 가능하도록 정의

arr1 = np.array([[1,2,3],
                 [4,5,6],
                  [7,8,9]])
arr2 = np.array([[2,2,2],
                 [2,2,2],
                  [2,2,2]])
print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
#덧셈
print(arr1 + arr2)
print(np.add(arr1, arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#뺄셈
print(arr1 - arr2)
print(np.subtract(arr1, arr2))


[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [ ]:
#곱셈 -> 내적 연산이 아닌 원소끼리의 곱
print(arr1 * arr2)
print(np.multiply(arr1, arr2))


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
import numpy as np
# 연산을 위해서는 두 배열의 shape이 같아야한다.

#numpy는 파이썬 기본 연산자를 n차원 배열, 즉 행렬이나 텐서 간의 연산이 가능하도록 정의

arr1 = np.array([[1,2,3],
                 [4,5,6],
                  [7,8,9]])
arr2 = np.array([[2,2,2],
                 [2,2,2],
                  [2,2,2]])
# print(arr1)
# print(arr2)

#나눗셈
print(arr1 / arr2)
print(np.divide(arr1, arr2))


[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [ ]:
#제곱
arr1 = np.array([[1,2,3],
                 [4,5,6],
                  [7,8,9]])
arr2 = np.array([[2,2,2],
                 [2,2,2],
                  [2,2,2]])
print(arr1 ** 2) #2제곱
print(arr1 ** 5) #5제곱
print(np.square(arr1)) #square를 이용하여 자기자신을 한번 곱셈

#제곱근
print(np.sqrt(arr1)) #square root 함수 사용 -> 각 원소 제곱근 출력

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[    1    32   243]
 [ 1024  3125  7776]
 [16807 32768 59049]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
#몫
print(arr1 // 2)

#나머지 -> 짝수들은 0 출력, 홀수들은 1 출력
print(arr1 % 2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]


3-2 배열의 연산2 : 내적(dot product) / 절댓값 / 올림 / 내림 / 반올림 / 버림

In [ ]:
import numpy as np
#dot product :  각각의 원소의 곱의합
#1차원 행렬
arr1 = np.array([2,3,4]) # 2곱하기1 3곱하기2 4곱하기3을 다 더한값 출력
arr2 = np.array([1,2,3])

print(np.dot(arr1,arr2))

20


In [ ]:
#2차원 행렬 dot product
arr1 = np.array([[1,2],
                 [4,5]])
arr2 = np.array([[1,2],
                 [0,3]])
print(np.dot(arr1, arr2))

[[ 1  8]
 [ 4 23]]


In [3]:
import numpy as np
arr1 = np.array([[1.932, -2.339],
                 [-4.145, 5.206]])
#절댓값 -> abs
print(np.abs(arr1))

#올림 => ceil
print(np.ceil(arr1))

#내림 -> floor
print(np.floor(arr1))

#반올림 -> round
print(np.round(arr1))

#버림 -> trunc
print(np.trunc(arr1))

[[1.932 2.339]
 [4.145 5.206]]
[[ 2. -2.]
 [-4.  6.]]
[[ 1. -3.]
 [-5.  5.]]
[[ 2. -2.]
 [-4.  5.]]
[[ 1. -2.]
 [-4.  5.]]


3-3 배열의 연산 : min/max/sum/mean/std/cumsum

In [4]:
arr = np.array([[1,2,3],
                [0,1,4]])
#min / max : 행렬의 원소중 가장 큰, 작은값 출력
print(np.min(arr))
print(np.max(arr))

#axis : 0 -> 각 열중 가장 큰, 작은값
print(arr.min(axis=0))
print(arr.max(axis=0))

#axis : 1 -> 각 행중 가장 큰, 작은값
print(arr.min(axis=1))
print(arr.max(axis=1))

0
4
[0 1 3]
[1 2 4]
[1 0]
[3 4]


In [5]:
arr = np.array([[1,2,3],
                [0,1,4]])
#sum : 모든 원소들의 합
print(np.sum(arr))

#각 열, 행 원소들의 합
print(arr.sum(axis=0)) #열
print(arr.sum(axis=1)) #행

#mean : 모든 원소들의 평균값
print(np.mean(arr))

#각 열, 행 원소들의 평균값
print(arr.mean(axis=0)) #열
print(arr.mean(axis=1)) #행

11
[1 3 7]
[6 5]
1.8333333333333333
[0.5 1.5 3.5]
[2.         1.66666667]


3-4 배열의 연산4 : 비교연산/삼각함수

In [8]:
#비교 연산 : True False로 출력
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[1,0,3],
                 [4,-2,9]])


#동등연산자
print(arr1 == arr2)

#대소연산자
print(arr1 > arr2)
print(arr1 >= arr2)

#배열 전체가 동일한지 여부를 비교
print(np.array_equal(arr1, arr2))

[[ True False  True]
 [ True False False]]
[[False  True False]
 [False  True False]]
[[ True  True  True]
 [ True  True False]]
False


In [6]:
#삼각 함수
arr1 = np.array([[1,2,3],
                 [4,5,6]])

#sin() -> 각 원소들의 sin값 출력수
print(np.sin(arr))
#con() -> 각 원소들의 cos값 출력
print(np.cos(arr))
#tan() -> 각 원소들의 tan값 출력
print(np.tan(arr))

[[ 0.84147098  0.90929743  0.14112001]
 [ 0.          0.84147098 -0.7568025 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [ 1.          0.54030231 -0.65364362]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 0.          1.55740772  1.15782128]]


3-5 브로드캐스팅

In [9]:
#기존에 배웠던 배열간 연산들은 연산을 할 배열의 쉐입이 서로 같아야 한다고 했음
#단순 연산을 위해 일일히 배열들 쉐입을 맞추는게 조금 번거러워 브로드캐스팅 기능을 사용

arr1 = np.array([[0,0,0],
                 [1,1,1],
                [2,2,2]])
arr2 = np.array([[5,6,7]])

print(arr1 + arr2) #두번쨰 배열이 첫번째 원소에 맞춰 확장되어 계산

arr1 = np.array([[1,1,1]])
arr2 = np.array([[0],
                 [1],
                 [2]])
print(arr1 + arr2) #첫번째 배열이 두번째에 맞추고 두번째 배열도 첫번째 배열에 맞춰 확장되어 계산

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


3-6 벡터 연산의 장점

In [ ]:
# 행렬 벡터 연산을 사용하게 되면 배열의 연산을 매우 빠르게 처리할 수 있는장점이 있다. for문과 비교
# 특히 딥러닝에서 선형대수 관련 연삳늘을 처리할 때 높은 연산 속도를 기대할 수 있다

#속도가 얼마나 차이나는지 확인을 해보기 위해 time이라는 모듈 import


In [ ]:
import time
import numpy as np
arr = np.arange(999999999)
sum = 0; #sum함수 만들기
before = time.time() # 연산을 하기 이전에 시간을 기록 / time모듈의 time함수 이용

#for -> for문을 이용해서 배열의 모든 원소들의 합 결과
for i in arr:
  sum += i #arr 모든 원소들을 sum함수에 더해주기
after = time.time() # 연산이 끝나면 시간을 다시 기록
print(sum, after - before, "초") #-> 연산에 걸렸던 총시간

499999998500000001 188.9275860786438 초


In [ ]:
#벡터 연산
before = time.time()
sum = np.sum(arr)
after = time.time()
print(sum, after - before, "초")

499999998500000001 0.7746479511260986 초


In [ ]:
arr1 = np.arange(999999999)
arr2 = np.arange(999999999)