4-1 1차원 배열의 정렬

In [1]:
import numpy as np

arr = np.random.randint(10, size=10)
print(arr)
# 오름차순 정렬
print(np.sort(arr))

#내림차순 정렬
print(np.sort(arr)[::-1])

# 원본 배열에는 정렬된 값들이 유지X
print(arr)

#arr배열자체를  sort함수로 정의
arr = np.sort(arr)
print(arr)

[2 8 8 2 3 3 5 1 7 4]
[1 2 2 3 3 4 5 7 8 8]
[8 8 7 5 4 3 3 2 2 1]
[2 8 8 2 3 3 5 1 7 4]
[1 2 2 3 3 4 5 7 8 8]


4-2 2차원 배열의 정렬

In [2]:
arr = np.random.randint(15, size= (3,4))
print(arr)

#행을 기준으로 오름차순 정렬
print(np.sort(arr, axis=1))
#열을 기준으로 오름차순 정렬
print(np.sort(arr, axis=0))

#axis = none
print(np.sort(arr, axis=None))

[[ 4 11  3  7]
 [ 5  8  1 14]
 [ 6  8 11 12]]
[[ 3  4  7 11]
 [ 1  5  8 14]
 [ 6  8 11 12]]
[[ 4  8  1  7]
 [ 5  8  3 12]
 [ 6 11 11 14]]
[ 1  3  4  5  6  7  8  8 11 11 12 14]
