5-1. 배열의 형태 변경1 : reshape()

In [ ]:
import numpy as np
#reshape() : 배열의 모양을 변경할 수 있는 함수

arr = np.arange(12)
print(arr, arr.ndim) #1차원 배열로 출력

arr = arr.reshape((3,4)) # 12개 원소 갯수는 맞아야함
print(arr, arr.ndim)
#arr = arr.reshape((2,3)) # 원소 갯수가 맞지 않아 size 안맞는 오류가 뜸

arr = arr.reshape((2,3,2)) #3차원 행렬로 변환 (텐서)
print(arr, arr.ndim)

arr = arr.reshape((2,2,1,3)) #4차원 행렬로 변환
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


In [ ]:
arr = np.arange(1, 13)
print(arr)

# 1차원 -> 2차원 배열
arr = arr.reshape(3, -1)

# 자동으로 3by4행렬로 출력
print(arr) #

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#차원을 증가시켜 reshape 할때 짚고 넘어가야할 문제

#Curse Of Dimensionality : 차원의 저주

#빅 데이터를 다루거나 딥러닝에서 발행하는 에러 : 차원이 증가하면서 학습 데이터 수가 차원의 수보다 적어지면서 모델의성능이 저하되는 현상



 5-2 배열의 형태 변경2 : resize(), ravel()

In [ ]:
import numpy as np

arr = np.arange(12)
print(arr)

#resize : reshape함수와 동일, 원본 데이터를 변경
arr.resize(3,4)
print(arr)

#ravel : 1차원 배열로 다시 변경
arr = arr.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


5-3 전치행렬


In [ ]:
#np.transpose(arr)
arr = np.array([[1,2],
                [3,4]])
print(arr.T)

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr.T)

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(arr.T)

[[1 3]
 [2 4]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 3 5]
 [2 4 6]]
