6-1. 배열에 원소 추가 및 삭제

In [ ]:
#insert
import numpy as np

#1차원 배열
arr = np.arange(1,9)
print(arr)

#insert
arr = np.insert(arr, 2, 50)
print(arr)

[1 2 3 4 5 6 7 8]
[ 1  2 50  3  4  5  6  7  8]


In [5]:
#insert
import numpy as np
#2차원 배열
arr = np.arange(1,13).reshape(3,4)

#axis값을 주지 않으면 1차원 배열로 변형 후 insert 함수 적용
arr = np.insert(arr, 2, 50)
print(arr)

#행을 기준으로 2번째 위치에 원소 50 삽입
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr, 2, 50, axis=0)
print(arr)

#열을 기준으로 2번째 위치에 원소 50 삽입
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr, 2, 50, axis=1)
print(arr)

[ 1  2 50  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]
[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]


In [3]:
#delete
import numpy as np
arr = np.arange(1,13).reshape(3,4)
print(arr)

#axis값을 주지 않으면 1차원 배열로 변형 후 delete 함수 적용
arr = np.delete(arr, 2)
print(arr)

#행을 기준으로 2번째 위치의 행 삭제
arr = np.arange(1,13).reshape(3,4)
arr = np.delete(arr, 2, axis=0)
print(arr)

#열을 기준으로 2번째 위치의 열 삭제
arr = np.arange(1,13).reshape(3,4)
arr = np.delete(arr, 2, axis=1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  4  5  6  7  8  9 10 11 12]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


6-2 배열간의 병합

In [4]:
#append
import numpy as np
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(1,13).reshape(3,4)

#행을 기준으로 arr1,2 배열 병합
arr3 = np.append(arr1, arr2, axis=0)
print(arr3)
#열을 기준으로 arr1,2 배열 병합
arr3 = np.append(arr1, arr2, axis=1)
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]


In [ ]:
#vstack, hstack
import numpy as np

arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

#vstack : 행을 기준으로 arr1,2 배열 병합
arr3 = np.vstack((arr1, arr2))
print(arr3)

#hstack : 열을 기준으로 arr1,2 배열 병합
arr3 = np.hstack((arr1, arr2))
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
